name: better_audio_capture
description: A audio capture plugin for Flutter.
version: 0.0.5
homepage: https://github.com/WangYng
repository: https://github.com/WangYng/better_audio_capture

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.github.wangyng.better_audio_capture
        pluginClass: BetterAudioCapturePlugin
      ios:
        pluginClass: BetterAudioCapturePlugin
